listen_addr: ":3001"
secret_token: "my-secret-token"
verify: false
webhooks:
  - path: "/webhook/app1"
    script: "/home/ubuntu/app1_update.sh"

  - path: "/webhook/app2"
    script: "/home/ubuntu/app2_update.sh"
